
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://18.141.192.153:5432/backend?currentSchema=app
    username: postgres
    password: LJnas5asdiu922!333
  servlet:
    multipart:
      enabled: true 
      max-file-size: 2MB
      max-request-size: 5MB