
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db?currentSchema=public
    username: _USERNAME_
    password: _PASSWORD_
  servlet:
    multipart:
      enabled: true 
      max-file-size: 2MB
      max-request-size: 5MB